version: '3.0'
  
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-5.6.5}
    environment:
     - ES_JAVA_OPTS=${ES_RAM:--Xmx1g -Xms1g}
    ports: ['9200:9200']
    networks: ['kibana-plugin-build']
  kibana:
    build:
      context: .
      args:
        - ES_TAG=v${ELASTIC_VERSION:-5.6.5}
        - NODE_IMAGE_VERSION=${KIBANA_NODE_VERSION:-6.11.5}
    image: samtecspg/kibana-plugin-dev:${ELASTIC_VERSION:-5.6.5}
    ports: ['5601:5601']
    networks: ['kibana-plugin-build']
    volumes:
      - ./plugin-dev:/plugin-dev
    depends_on:
      - elasticsearch
networks:
  kibana-plugin-build:
